### ISSUE TITLE
Nodemon

### ISSUE THREAD

**Issue by valkyrienyanko** [jonassterud/Cosmos#11]
Nodemon will auto restart the bot whenever changes are saved and made to a file. This speeds up development, let me know if you want me to implement this in the start up script in package.json.

**Comment by jonassterud** [comment]
Oh yeah, absolutely. That sounds very useful.

**Comment by valkyrienyanko** [comment]
Merged with #10

**Comment by valkyrienyanko** [comment]
I'm not sure if you use `node` or `yarn` so I deleted `yarn.lock` and assumed you're using `node`.

**Comment by valkyrienyanko** [comment]
iirc you had a package-lock.json to start off with so that's why I assumed you're using `node`

**Comment by jonassterud** [comment]
Yeah, that's correct. Me and @SebastianRefsnes both use `node`.

**Comment by valkyrienyanko** [comment]
You should try out `yarn`, I find it to be much better then `node` and blazing fast. 

Install it with `npm i yarn -g`.

If you do like it and use it over `node`, remember to remove `package-lock.json` and remove `yarn.lock` from `.gitignore`.

https://classic.yarnpkg.com/en/docs/usage

**Comment by jonassterud** [comment]
I'll try it. But `yarn` is a package manager right? You install a package manager with another package manager? Or should I just install the `.msi` file from [here](https://classic.yarnpkg.com/en/docs/install#windows-stable)? What do you think?

**Comment by valkyrienyanko** [comment]
I never tried the `.msi` before, I always use `npm i yarn -g` to install it. Then I do stuff like `yarn add package` or `yarn install`, etc.

**Comment by jonassterud** [comment]
Ok. I'll try it tomorrow.
